
package vista;

/**
 *
 * @author natan
 */
public class MedRegistrarHistoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form MedRegistrar
     */
    public MedRegistrarHistoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtdueñoapell = new javax.swing.JTextField();
        txtdueñonombre = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtdueñodni = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtdueñocell = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        btnREGISTRAR_HISTORIA = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtid_mascota = new javax.swing.JTextField();
        txtmascostasex = new javax.swing.JTextField();
        txtmascostanom = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtmascotaesp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btnBUSCAR_PACIENTE = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txatratamiento = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHISTORIA = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txadiagnostico = new javax.swing.JTextArea();
        btnACTUALIZAR = new javax.swing.JButton();
        btnELIMINAR = new javax.swing.JButton();
        txtid_historia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnNUEVA_HISTORIA = new javax.swing.JButton();
        txtdetallecita = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRESUMEN = new javax.swing.JTextArea();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 34)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(75, 77, 81));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR HISTORIA CLINICA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1480, 50));

        jPanel4.setBackground(new java.awt.Color(182, 182, 182));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1516, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1520, 30));

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DATOS DE LA MASCOTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdueñoapell.setEditable(false);
        txtdueñoapell.setBackground(new java.awt.Color(241, 241, 241));
        txtdueñoapell.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtdueñoapell.setBorder(null);
        txtdueñoapell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdueñoapellActionPerformed(evt);
            }
        });
        jPanel2.add(txtdueñoapell, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 30));

        txtdueñonombre.setEditable(false);
        txtdueñonombre.setBackground(new java.awt.Color(241, 241, 241));
        txtdueñonombre.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtdueñonombre.setBorder(null);
        jPanel2.add(txtdueñonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 290, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(29, 26, 26));
        jLabel23.setText("NOMBRE DEL DUEÑO");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(29, 26, 26));
        jLabel24.setText("APELLIDO");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(29, 26, 26));
        jLabel25.setText("N° DE DNI");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        txtdueñodni.setEditable(false);
        txtdueñodni.setBackground(new java.awt.Color(241, 241, 241));
        txtdueñodni.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtdueñodni.setBorder(null);
        txtdueñodni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdueñodniActionPerformed(evt);
            }
        });
        jPanel2.add(txtdueñodni, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 290, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(29, 26, 26));
        jLabel26.setText("CELULAR");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtdueñocell.setEditable(false);
        txtdueñocell.setBackground(new java.awt.Color(241, 241, 241));
        txtdueñocell.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtdueñocell.setBorder(null);
        txtdueñocell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdueñocellActionPerformed(evt);
            }
        });
        jPanel2.add(txtdueñocell, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 290, 30));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 290, 10));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 290, 10));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 290, 10));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 290, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 370, 300));

        btnREGISTRAR_HISTORIA.setBackground(new java.awt.Color(75, 77, 81));
        btnREGISTRAR_HISTORIA.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnREGISTRAR_HISTORIA.setForeground(new java.awt.Color(255, 255, 255));
        btnREGISTRAR_HISTORIA.setText("GUARDAR");
        btnREGISTRAR_HISTORIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREGISTRAR_HISTORIAActionPerformed(evt);
            }
        });
        jPanel1.add(btnREGISTRAR_HISTORIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 380, 30));

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "DATOS DE LA MASCOTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(29, 26, 26));
        jLabel27.setText("ID MASCOTA");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(29, 26, 26));
        jLabel29.setText("ESPECIE");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtid_mascota.setEditable(false);
        txtid_mascota.setBackground(new java.awt.Color(241, 241, 241));
        txtid_mascota.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtid_mascota.setBorder(null);
        txtid_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_mascotaActionPerformed(evt);
            }
        });
        jPanel3.add(txtid_mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 290, 30));

        txtmascostasex.setEditable(false);
        txtmascostasex.setBackground(new java.awt.Color(241, 241, 241));
        txtmascostasex.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtmascostasex.setBorder(null);
        txtmascostasex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmascostasexActionPerformed(evt);
            }
        });
        jPanel3.add(txtmascostasex, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 290, 30));

        txtmascostanom.setEditable(false);
        txtmascostanom.setBackground(new java.awt.Color(241, 241, 241));
        txtmascostanom.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtmascostanom.setBorder(null);
        jPanel3.add(txtmascostanom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 290, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(29, 26, 26));
        jLabel30.setText("SEXO");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtmascotaesp.setEditable(false);
        txtmascotaesp.setBackground(new java.awt.Color(241, 241, 241));
        txtmascotaesp.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtmascotaesp.setBorder(null);
        txtmascotaesp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmascotaespActionPerformed(evt);
            }
        });
        jPanel3.add(txtmascotaesp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 290, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(29, 26, 26));
        jLabel28.setText("NOMBRE DEL PACIENTE");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 290, 10));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 290, 10));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 290, 10));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 290, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 370, 300));

        btnBUSCAR_PACIENTE.setBackground(new java.awt.Color(75, 77, 81));
        btnBUSCAR_PACIENTE.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnBUSCAR_PACIENTE.setForeground(new java.awt.Color(255, 255, 255));
        btnBUSCAR_PACIENTE.setText("BUSCAR CITA");
        btnBUSCAR_PACIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBUSCAR_PACIENTEActionPerformed(evt);
            }
        });
        jPanel1.add(btnBUSCAR_PACIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 760, 30));

        jPanel7.setBackground(new java.awt.Color(241, 241, 241));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "TRATAMIENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txatratamiento.setColumns(20);
        txatratamiento.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txatratamiento.setRows(5);
        jScrollPane4.setViewportView(txatratamiento);

        jPanel7.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 160));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 380, 210));

        jPanel8.setBackground(new java.awt.Color(188, 151, 77));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHISTORIA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHISTORIA.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblHISTORIA.getTableHeader().setResizingAllowed(false);
        tblHISTORIA.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblHISTORIA);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 280));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 730, 300));

        jPanel11.setBackground(new java.awt.Color(241, 241, 241));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "DIAGNOSTICO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 1, 16), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txadiagnostico.setColumns(20);
        txadiagnostico.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txadiagnostico.setRows(5);
        jScrollPane3.setViewportView(txadiagnostico);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 340, 160));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 380, 210));

        btnACTUALIZAR.setBackground(new java.awt.Color(75, 77, 81));
        btnACTUALIZAR.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnACTUALIZAR.setForeground(new java.awt.Color(255, 255, 255));
        btnACTUALIZAR.setText("ACTUALIZAR");
        jPanel1.add(btnACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 360, 30));

        btnELIMINAR.setBackground(new java.awt.Color(75, 77, 81));
        btnELIMINAR.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnELIMINAR.setForeground(new java.awt.Color(255, 255, 255));
        btnELIMINAR.setText("ELIMINAR");
        jPanel1.add(btnELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 380, 360, 30));

        txtid_historia.setBackground(new java.awt.Color(255, 255, 255));
        txtid_historia.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtid_historia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtid_historia.setBorder(null);
        jPanel1.add(txtid_historia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("DETALLE DE CITA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 190, -1));

        btnNUEVA_HISTORIA.setBackground(new java.awt.Color(75, 77, 81));
        btnNUEVA_HISTORIA.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnNUEVA_HISTORIA.setForeground(new java.awt.Color(255, 255, 255));
        btnNUEVA_HISTORIA.setText("NUEVA HISTORIA");
        jPanel1.add(btnNUEVA_HISTORIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 710, 370, 30));

        txtdetallecita.setBackground(new java.awt.Color(255, 255, 255));
        txtdetallecita.setFont(new java.awt.Font("Dubai", 0, 16)); // NOI18N
        txtdetallecita.setBorder(null);
        txtdetallecita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdetallecitaActionPerformed(evt);
            }
        });
        jPanel1.add(txtdetallecita, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 380, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID_HISTORIA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 180, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 380, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 180, 10));

        jPanel5.setBackground(new java.awt.Color(241, 241, 241));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaRESUMEN.setEditable(false);
        txaRESUMEN.setColumns(20);
        txaRESUMEN.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        txaRESUMEN.setRows(5);
        jScrollPane1.setViewportView(txaRESUMEN);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 330));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 730, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdueñoapellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdueñoapellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdueñoapellActionPerformed

    private void txtdueñodniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdueñodniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdueñodniActionPerformed

    private void txtdueñocellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdueñocellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdueñocellActionPerformed

    private void txtid_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_mascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_mascotaActionPerformed

    private void txtmascostasexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmascostasexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmascostasexActionPerformed

    private void txtmascotaespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmascotaespActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmascotaespActionPerformed

    private void btnREGISTRAR_HISTORIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREGISTRAR_HISTORIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnREGISTRAR_HISTORIAActionPerformed

    private void txtdetallecitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdetallecitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdetallecitaActionPerformed

    private void btnBUSCAR_PACIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBUSCAR_PACIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBUSCAR_PACIENTEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnACTUALIZAR;
    public javax.swing.JButton btnBUSCAR_PACIENTE;
    public javax.swing.JButton btnELIMINAR;
    public javax.swing.JButton btnNUEVA_HISTORIA;
    public javax.swing.JButton btnREGISTRAR_HISTORIA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTable tblHISTORIA;
    public javax.swing.JTextArea txaRESUMEN;
    public javax.swing.JTextArea txadiagnostico;
    public javax.swing.JTextArea txatratamiento;
    public javax.swing.JTextField txtdetallecita;
    public javax.swing.JTextField txtdueñoapell;
    public javax.swing.JTextField txtdueñocell;
    public javax.swing.JTextField txtdueñodni;
    public javax.swing.JTextField txtdueñonombre;
    public javax.swing.JTextField txtid_historia;
    public javax.swing.JTextField txtid_mascota;
    public javax.swing.JTextField txtmascostanom;
    public javax.swing.JTextField txtmascostasex;
    public javax.swing.JTextField txtmascotaesp;
    // End of variables declaration//GEN-END:variables
}
